# Generated by Django 5.2.1 on 2025-08-02 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_creer_projet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_exporter_donnees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_gerer_utilisateurs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_modifier_projet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_supprimer_projet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='peut_voir_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('GESTIONNAIRE', 'Gestionnaire de Projet'), ('ADMINISTRATEUR', 'Administrateur Système'), ('CONSULTANT', 'Consultant'), ('SUPERVISEUR', 'Superviseur'), ('OBSERVATEUR', 'Observateur Public')], default='GESTIONNAIRE', max_length=20),
        ),
    ]
