# Generated by Django 5.2.1 on 2025-08-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilutilisateur_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('GESTIONNAIRE', 'Gestionnaire de Projet'), ('ADMINISTRATEUR', 'Administrateur Système'), ('CONSULTANT', 'Consultant')], default='GESTIONNAIRE', max_length=20),
        ),
    ]
