# Generated by Django 5.2.1 on 2025-08-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilutilisateur_role'),
        ('users', '0003_update_roles'),
    ]

    operations = [
    ]
