# Generated by Django 5.2.4 on 2025-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilutilisateur_role'),
        ('users', '0003_update_roles'),
    ]

    operations = [
    ]
