# Generated by Django 5.2.1 on 2025-08-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250809_1108'),
        ('users', '0004_merge_20250818_2055'),
    ]

    operations = [
    ]
