# Generated by Django 5.2.1 on 2025-07-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EN_ATTENTE', 'En attente'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('budget_prevue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL)),
                ('membres', models.ManyToManyField(blank=True, related_name='projets_participes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succès')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PREVU', 'Prévu'), ('REEL', 'Réel'), ('AJUSTEMENT', 'Ajustement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('priorite', models.IntegerField(default=1, help_text='1 = Très haute, 5 = Très basse')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], max_length=20)),
                ('probabilite', models.IntegerField(help_text='Probabilité en pourcentage (0-100)')),
                ('impact', models.TextField()),
                ('mesures_mitigation', models.TextField(blank=True)),
                ('date_identification', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='projects.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Risques',
            },
        ),
    ]
