# Generated by Django 5.2.1 on 2025-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='longitude',
        ),
        migrations.AddField(
            model_name='projet',
            name='departement',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DAKAR', 'Dakar'), ('GUEDIAWAYE', 'Guédiawaye'), ('PIKINE', 'Pikine'), ('RUFISQUE', 'Rufisque'), ('THIES', 'Thiès'), ('MBOUR', "M'bour"), ('TIVAOUANE', 'Tivaouane'), ('DIOURBEL', 'Diourbel'), ('BAMBEY', 'Bambey'), ('MBACKE', 'Mbacké'), ('FATICK', 'Fatick'), ('FOUNDIOUGNE', 'Foundiougne'), ('GOSSAS', 'Gossas'), ('KAOLACK', 'Kaolack'), ('GUINGUINEO', 'Guinguinéo'), ('NIORO', 'Nioro du Rip'), ('KOLDA', 'Kolda'), ('MEDINA_YORO_FOULA', 'Médina Yoro Foulah'), ('VELINGARA', 'Vélingara'), ('LOUGA', 'Louga'), ('KEBEMER', 'Kébémer'), ('LINGUERE', 'Linguère'), ('MATAM', 'Matam'), ('KANEL', 'Kanel'), ('RANEROU', 'Ranérou'), ('SAINT_LOUIS', 'Saint-Louis'), ('DAGANA', 'Dagana'), ('PODOR', 'Podor'), ('SEDHIOU', 'Sédhiou'), ('BOUNKILING', 'Bounkiling'), ('GOUDOMP', 'Goudomp'), ('TAMBACOUNDA', 'Tambacounda'), ('BAKEL', 'Bakel'), ('GOUDIRY', 'Goudiry'), ('KOUMPENTOUM', 'Koumpentoum'), ('ZIGUINCHOR', 'Ziguinchor'), ('BIGNONA', 'Bignona'), ('OUSSOUYE', 'Oussouye'), ('KAFFRINE', 'Kaffrine'), ('BIRKILANE', 'Birkilane'), ('MALEM_HODAR', 'Malem Hodar'), ('KEDOUGOU', 'Kédougou'), ('SALEMATA', 'Salémata'), ('SARAYA', 'Saraya')], max_length=30),
        ),
        migrations.AddField(
            model_name='projet',
            name='region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DAKAR', 'Dakar'), ('THIES', 'Thiès'), ('DIOURBEL', 'Diourbel'), ('FATICK', 'Fatick'), ('KAOLACK', 'Kaolack'), ('KOLDA', 'Kolda'), ('LOUGA', 'Louga'), ('MATAM', 'Matam'), ('SAINT_LOUIS', 'Saint-Louis'), ('SEDHIOU', 'Sédhiou'), ('TAMBACOUNDA', 'Tambacounda'), ('ZIGUINCHOR', 'Ziguinchor'), ('KAFFRINE', 'Kaffrine'), ('KEDOUGOU', 'Kédougou')], max_length=20),
        ),
    ]
