# Generated by Django 5.2.1 on 2025-08-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_lat_long_add_region_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='etape_actuelle',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PREPARATION', 'Préparation du terrain'), ('FONDATIONS', 'Fondations'), ('GROS_OEUVRE', 'Gros œuvre'), ('SECOND_OEUVRE', 'Second œuvre'), ('FINITIONS', 'Finitions'), ('AMENAGEMENT', 'Aménagement extérieur'), ('RECEPTION', 'Réception des travaux')], max_length=20),
        ),
    ]
