# Generated by Django 5.2.1 on 2025-08-25 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0005_projet_etape_actuelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('UPLOAD', 'Upload de fichier'), ('DOWNLOAD', 'Téléchargement'), ('STATUS_CHANGE', 'Changement de statut'), ('ASSIGNMENT', 'Attribution'), ('COMMENT', 'Commentaire'), ('NOTIFICATION', 'Notification')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('context', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='projects.projet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traçabilité',
                'verbose_name_plural': 'Traçabilités',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='projects_au_timesta_88a931_idx'), models.Index(fields=['action'], name='projects_au_action_ba1aa7_idx'), models.Index(fields=['user'], name='projects_au_user_id_d39622_idx'), models.Index(fields=['projet'], name='projects_au_projet__b2275d_idx'), models.Index(fields=['resource_type'], name='projects_au_resourc_8f9902_idx'), models.Index(fields=['content_type', 'object_id'], name='projects_au_content_e5b14b_idx')],
            },
        ),
    ]
