# Generated by Django 5.2.1 on 2025-08-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
