# Generated by Django 5.2.1 on 2025-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_phase_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nom de la personne responsable de cette phase', max_length=255),
        ),
    ]
