# Generated by Django 5.2.1 on 2025-08-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_phase_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='responsable_telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du responsable (ex: +221 77 123 45 67)', max_length=20),
        ),
    ]
