# Generated by Django 5.2.1 on 2025-07-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLAN', 'Plan'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('PV', 'PV de réception')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.projet')),
            ],
        ),
    ]
